
name: sixvalley_delivery_boy
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  get: ^4.1.4
  http: ^1.2.1
  shared_preferences:
  dio: ^5.4.3+1
  google_maps_flutter: ^2.0.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  url_launcher: ^6.0.2
  url_strategy: ^0.2.0
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.0.2
  vibration: ^1.7.4-nullsafety.0
  shimmer: ^3.0.0
  flutter_widget_from_html_core: ^0.14.12
  image_picker: ^1.1.1
  intl: ^0.19.0
  connectivity: ^3.0.6
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  country_code_picker: ^3.0.0
  expandable: ^5.0.1
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^2.0.0
  timeago: ^3.3.0
  dotted_border: ^2.0.0+2
  expandable_bottom_sheet: ^1.1.1+1
  syncfusion_flutter_datepicker: ^25.2.5
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^5.2.0
  flutter_html: ^3.0.0-alpha.3
  pin_code_fields: ^8.0.1
  readmore: ^3.0.0
  cached_network_image:
  flutter_native_splash: ^2.3.2
  permission_handler: ^11.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700